Automated deployment to PyPI on release
MDAnalysis/PathSimAnalysis pull request #3
Opened 2023-10-11 21:39 UTC by ianmkenney

The package should automatically be uploaded to PyPI when a release is made.

2023-10-11 21:40 UTC, ianmkenney commented
@IAlibay Could you take a look at the `deploy.yaml` workflow? I took it from `mdaencore`, which you made. If this does the job, then it should be straightforward to move to other MDAKits.

2023-10-11 21:43 UTC, IAlibay commented
> @IAlibay Could you take a look at the `deploy.yaml` workflow? I took it from `mdaencore`, which you made. If this does the job, then it should be straightforward to move to other MDAKits.

By other MDAKit you mean "other Cython using kits" right? i.e. cibuildwheels isn't suitable for pure python kits

2023-10-11 21:44 UTC, IAlibay requested changes
For pure python you should instead use the pypi-deployment action (I assume PSA is indeed pure python).

2023-10-11 21:45 UTC, ianmkenney commented
I figured it wouldn't be the best reference for that reason, I'll just rewrite from scratch then! Thanks

2023-10-12 02:27 UTC, IAlibay commented
> I figured it wouldn't be the best reference for that reason, I'll just rewrite from scratch then! Thanks

Please don't rewrite from scratch and use the reusable action - it is there so we can align across all our repos

2023-10-12 12:49 UTC, IAlibay commented on .github/workflows/deploy.yaml
Essentially you want to just have this workflow file: https://github.com/MDAnalysis/mda-xdrlib/blob/main/.github/workflows/deploy.yaml

2023-10-13 18:19 UTC, orbeckst requested changes
I assume we can't test if it works without merging? So we'll merge this and then do a 1.0.1 release?

The PyPi metadata doesn't have a link to a documentation page. Enable https://github.com/MDAnalysis/PathSimAnalysis/blob/3267deeb0f436732b69783d88a49ba7a34f07687/pyproject.toml#L42-L44 for docs and source.

MDAnalysis is not the only dependency in https://github.com/MDAnalysis/PathSimAnalysis/blob/3267deeb0f436732b69783d88a49ba7a34f07687/pyproject.toml#L21 — we also have
```python
import numpy as np
from scipy import spatial, cluster
from scipy.spatial.distance import directed_hausdorff
import matplotlib
```
so they all need to be explicitly listed in `pyproject.toml` (important for PyPi!) and also in [devtools/conda-envs/test_env.yaml](https://github.com/MDAnalysis/PathSimAnalysis/blob/main/devtools/conda-envs/test_env.yaml).

2023-10-13 19:16 UTC, orbeckst approved these changes
This _looks_ ok to me. Let's first see if https://github.com/MDAnalysis/waterdynamics/pull/8 works, given that it's essentially implementing the same workflow. If any problems emerge there then we can fix them here, too.

Assuming all is fine, we can then do a 1.0.1 here.

2023-10-13 22:36 UTC, merged